# Generated by Django 5.2.17 on 2026-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_tag_tasktype_task'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed', 'deadline'], name='task_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
    ]
